/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ss8;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.border.TitledBorder;

/**
 *
 * @author QQ
 */
public class Login extends javax.swing.JFrame {
    Locale LocaleEN, LocaleVI;
    ResourceBundle resourceCurrent, resourceUS, resourceVI;
    
    
    public void updateGUI(){
        this.setTitle(resourceCurrent.getString("title"));
        this.lblTitle.setText(resourceCurrent.getString("lblTitle"));
        this.pnlLanguage.setBorder(new TitledBorder(resourceCurrent.getString("pnlLanguage")));
        this.raEnglish.setText(resourceCurrent.getString("raEnglish"));
        this.raVietnamese.setText(resourceCurrent.getString("raVietnamese"));
        this.lblUsername.setText(resourceCurrent.getString("lblUsername"));
        this.lblPassword.setText(resourceCurrent.getString("lblPassword"));
        this.btnSignIn.setText(resourceCurrent.getString("btnSignIn"));
        
    }
    
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        LocaleEN = new Locale("en", "US");
        LocaleVI = new Locale("vi", "VI");
        resourceUS = ResourceBundle.getBundle("ss8/"+"GUI_en_US",LocaleEN);
        resourceVI = ResourceBundle.getBundle("ss8/"+"GUI_vi_VI",LocaleVI);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        pnlLanguage = new javax.swing.JPanel();
        raEnglish = new javax.swing.JRadioButton();
        raVietnamese = new javax.swing.JRadioButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnSignIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 153));
        lblTitle.setText("Login Form");

        pnlLanguage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Language", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12), new java.awt.Color(0, 153, 51))); // NOI18N

        buttonGroup1.add(raEnglish);
        raEnglish.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        raEnglish.setSelected(true);
        raEnglish.setText("English");
        raEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raEnglishActionPerformed(evt);
            }
        });

        buttonGroup1.add(raVietnamese);
        raVietnamese.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        raVietnamese.setText("Vietnamese");
        raVietnamese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raVietnameseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLanguageLayout = new javax.swing.GroupLayout(pnlLanguage);
        pnlLanguage.setLayout(pnlLanguageLayout);
        pnlLanguageLayout.setHorizontalGroup(
            pnlLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLanguageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(raEnglish)
                .addGap(12, 12, 12)
                .addComponent(raVietnamese)
                .addContainerGap())
        );
        pnlLanguageLayout.setVerticalGroup(
            pnlLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLanguageLayout.createSequentialGroup()
                .addGroup(pnlLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raEnglish)
                    .addComponent(raVietnamese))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        lblUsername.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblUsername.setText("Username:");
        lblUsername.setToolTipText("");

        lblPassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblPassword.setText("Password:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnSignIn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(0, 102, 153));
        btnSignIn.setText("Sign In");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(pnlLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSignIn))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblTitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pnlLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raEnglishActionPerformed
        // TODO add your handling code here:
        
        resourceCurrent = resourceUS;
        
        updateGUI();
    }//GEN-LAST:event_raEnglishActionPerformed

    private void raVietnameseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raVietnameseActionPerformed
        // TODO add your handling code here:
        
        resourceCurrent = resourceVI;
        
        updateGUI();
    }//GEN-LAST:event_raVietnameseActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlLanguage;
    private javax.swing.JRadioButton raEnglish;
    private javax.swing.JRadioButton raVietnamese;
    // End of variables declaration//GEN-END:variables
}
