/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ss2;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author QQ
 */
public class DateDemo extends javax.swing.JFrame {

    public void getDate(){
        int day = sliderDay.getValue();
        int month = sliderMonth.getValue();
        int year = sliderYear.getValue();
        
        Calendar c = Calendar.getInstance(); // Lấy lịch theo giờ, vùng hiện tại
        //Ngày, năm chạy từ 1, tháng chạy từ 0-11 nên phải set tháng -1, để hiển thị tháng đúng với hiện tại
        //Ví dụ: set tháng là 11 thì nó calendar sẽ lấy tháng 12 nên phải trừ 1
        c.set(year, month-1, day); //Đặt ngày tháng năm cho đối tượng calendar dựa trên slider
        Date date = c.getTime(); // Gán giờ giấc của calendar vào date
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE"); // Tạo định dạng ngày trong tuần
        String dayOfWeek = sdf.format(date); // Chuyển định dạng ngày tháng năm => ngày trong tuần, gán giá trị vào biến string
//        System.out.println(dayOfWeek); // Test kết quả xuất ra màn hình: Monday, Tuesday , Wednesday, ... 
//        System.out.println(date); // Test date
        lblTextarea.setText(dayOfWeek+", "+day+"/"+month+"/"+year);
        
    }
    
    
    
    /**
     * Creates new form DateDemo
     */
    public DateDemo() {
        initComponents();
        getDate(); // Hiển thị ngày tháng năm sau khi load components
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTextarea = new javax.swing.JPanel();
        lblTextarea = new javax.swing.JLabel();
        pnlYear = new javax.swing.JPanel();
        sliderYear = new javax.swing.JSlider();
        pnlMonth = new javax.swing.JPanel();
        sliderMonth = new javax.swing.JSlider();
        pnlDay = new javax.swing.JPanel();
        sliderDay = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Date Demo");

        pnlTextarea.setBorder(javax.swing.BorderFactory.createTitledBorder("Text Area"));

        lblTextarea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTextarea.setText("asd");
        lblTextarea.setToolTipText("");

        javax.swing.GroupLayout pnlTextareaLayout = new javax.swing.GroupLayout(pnlTextarea);
        pnlTextarea.setLayout(pnlTextareaLayout);
        pnlTextareaLayout.setHorizontalGroup(
            pnlTextareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextareaLayout.createSequentialGroup()
                .addGap(0, 96, Short.MAX_VALUE)
                .addComponent(lblTextarea, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTextareaLayout.setVerticalGroup(
            pnlTextareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextareaLayout.createSequentialGroup()
                .addComponent(lblTextarea, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlYear.setBorder(javax.swing.BorderFactory.createTitledBorder("Year"));

        sliderYear.setMajorTickSpacing(5);
        sliderYear.setMaximum(2020);
        sliderYear.setMinimum(2000);
        sliderYear.setPaintLabels(true);
        sliderYear.setPaintTicks(true);
        sliderYear.setValue(2010);
        sliderYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderYearStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlYearLayout = new javax.swing.GroupLayout(pnlYear);
        pnlYear.setLayout(pnlYearLayout);
        pnlYearLayout.setHorizontalGroup(
            pnlYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlYearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sliderYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlYearLayout.setVerticalGroup(
            pnlYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlYearLayout.createSequentialGroup()
                .addComponent(sliderYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMonth.setBorder(javax.swing.BorderFactory.createTitledBorder("Month"));

        sliderMonth.setMajorTickSpacing(1);
        sliderMonth.setMaximum(12);
        sliderMonth.setMinimum(1);
        sliderMonth.setPaintLabels(true);
        sliderMonth.setPaintTicks(true);
        sliderMonth.setValue(3);
        sliderMonth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMonthStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlMonthLayout = new javax.swing.GroupLayout(pnlMonth);
        pnlMonth.setLayout(pnlMonthLayout);
        pnlMonthLayout.setHorizontalGroup(
            pnlMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sliderMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMonthLayout.setVerticalGroup(
            pnlMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMonthLayout.createSequentialGroup()
                .addComponent(sliderMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlDay.setBorder(javax.swing.BorderFactory.createTitledBorder("Day"));

        sliderDay.setMajorTickSpacing(5);
        sliderDay.setMaximum(31);
        sliderDay.setMinimum(1);
        sliderDay.setPaintLabels(true);
        sliderDay.setPaintTicks(true);
        sliderDay.setToolTipText("");
        sliderDay.setValue(16);
        sliderDay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDayStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlDayLayout = new javax.swing.GroupLayout(pnlDay);
        pnlDay.setLayout(pnlDayLayout);
        pnlDayLayout.setHorizontalGroup(
            pnlDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sliderDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDayLayout.setVerticalGroup(
            pnlDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDayLayout.createSequentialGroup()
                .addComponent(sliderDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pnlTextarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTextarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderYearStateChanged
        // TODO add your handling code here:
        this.getDate();
    }//GEN-LAST:event_sliderYearStateChanged

    private void sliderMonthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMonthStateChanged
        // TODO add your handling code here:
        this.getDate();
    }//GEN-LAST:event_sliderMonthStateChanged

    private void sliderDayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDayStateChanged
        // TODO add your handling code here:
        this.getDate();
    }//GEN-LAST:event_sliderDayStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTextarea;
    private javax.swing.JPanel pnlDay;
    private javax.swing.JPanel pnlMonth;
    private javax.swing.JPanel pnlTextarea;
    private javax.swing.JPanel pnlYear;
    private javax.swing.JSlider sliderDay;
    private javax.swing.JSlider sliderMonth;
    private javax.swing.JSlider sliderYear;
    // End of variables declaration//GEN-END:variables
}
